version = "0.0.0"
lastOpenWorkspaceName = ""
externalSaveWorkspacePath = []
host = "localhost"
port = 8080
workspace-state = "-43.285696311134416,380.67169037844764,0.6659540734155751"
side-panel-state-left = "built_in_tool_workspace,400,on"
side-panel-state-right = ",0,on"
